import{a as S,S as E,i as c}from"./assets/vendor-BkC4bTqC.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const q="29372998-77c4088f99339c8fc310ed4d5",B="https://pixabay.com/api/",M=15;async function f(s,r=1){try{return(await S.get(B,{params:{key:q,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:M}})).data}catch(o){throw console.error(o),o}}const m=document.querySelector(".gallery"),y=document.querySelector(".loader"),h=document.querySelector(".load-more-btn"),P=new E(".gallery a",{captionsData:"alt",captionDelay:250});function g(s){const r=s.map(({webformatURL:o,largeImageURL:i,tags:e,likes:t,views:a,comments:v,downloads:w})=>`
    <a href="${i}" class="gallery-link">
      <div class="photo-card">
        <img src="${o}" alt="${e}" loading="lazy" />
        <div class="info">
          <p><span>❤️ Likes:</span><span>${t}</span></p>
          <p><span>👁 Views:</span><span>${a}</span></p>
          <p><span>💬 Comments:</span><span>${v}</span></p>
          <p><span>⬇ Downloads:</span><span>${w}</span></p>
        </div>
      </div>
    </a>
  `).join("");m.insertAdjacentHTML("beforeend",r),P.refresh()}function $(){m.innerHTML=""}function L(){y.classList.add("visible")}function l(){y.classList.remove("visible")}function b(){h.classList.add("visible")}function d(){h.classList.remove("visible")}const O=document.querySelector(".form"),x=document.querySelector(".load-more-btn");let n=1,u="",p=0;O.addEventListener("submit",A);x.addEventListener("click",H);async function A(s){s.preventDefault();const r=s.target.elements["search-text"].value.trim();if(r){u=r,n=1,$(),d(),L();try{const o=await f(u,n);if(p=o.totalHits,o.hits.length===0){c.warning({title:"No results",message:"Sorry, no images found."}),l();return}g(o.hits),n*15<p&&b()}catch{c.error({title:"Error",message:"Failed to fetch images."})}finally{l()}}}async function H(){n++,L(),d();try{const s=await f(u,n);g(s.hits);const{height:r}=document.querySelector(".gallery a").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),n*15>=p?(d(),c.info({title:"End",message:"We're sorry, but you've reached the end of search results."})):b()}catch{c.error({title:"Error",message:"Failed to fetch more images."})}finally{l()}}
//# sourceMappingURL=index.js.map
