import{S as $,i as c}from"./assets/vendor-BrddEoy-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const S="29372998-77c4088f99339c8fc310ed4d5",E="https://pixabay.com/api/",q=15;async function p(n,r=1){const s=`${E}?key=${S}&q=${encodeURIComponent(n)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${q}`;try{const o=await fetch(s);if(!o.ok)throw new Error(`HTTP error: ${o.status}`);return await o.json()}catch(o){throw console.error(o),o}}const m=document.querySelector(".gallery"),y=document.querySelector(".loader"),h=document.querySelector(".load-more-btn"),P=new $(".gallery a",{captionsData:"alt",captionDelay:250});function g(n){const r=n.map(({webformatURL:s,largeImageURL:o,tags:e,likes:t,views:i,comments:v,downloads:w})=>`
    <a href="${o}" class="gallery-link">
      <div class="photo-card">
        <img src="${s}" alt="${e}" loading="lazy" />
        <div class="info">
          <p><span>❤️ Likes:</span><span>${t}</span></p>
          <p><span>👁 Views:</span><span>${i}</span></p>
          <p><span>💬 Comments:</span><span>${v}</span></p>
          <p><span>⬇ Downloads:</span><span>${w}</span></p>
        </div>
      </div>
    </a>
  `).join("");m.insertAdjacentHTML("beforeend",r),P.refresh()}function B(){m.innerHTML=""}function L(){y.classList.add("visible")}function l(){y.classList.remove("visible")}function b(){h.classList.add("visible")}function d(){h.classList.remove("visible")}const M=document.querySelector(".form"),H=document.querySelector(".load-more-btn");let a=1,u="",f=0;M.addEventListener("submit",O);H.addEventListener("click",A);async function O(n){n.preventDefault();const r=n.target.elements["search-text"].value.trim();if(r){u=r,a=1,B(),d(),L();try{const s=await p(u,a);if(f=s.totalHits,s.hits.length===0){c.warning({title:"No results",message:"Sorry, no images found."}),l();return}g(s.hits),a*15<f&&b()}catch{c.error({title:"Error",message:"Failed to fetch images."})}finally{l()}}}async function A(){a++,L(),d();try{const n=await p(u,a);g(n.hits);const{height:r}=document.querySelector(".gallery a").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),a*15>=f?(d(),c.info({title:"End",message:"We're sorry, but you've reached the end of search results."})):b()}catch{c.error({title:"Error",message:"Failed to fetch more images."})}finally{l()}}
//# sourceMappingURL=index.js.map
